// Mocks generated by Mockito 5.4.4 from annotations
// in meal_planner/test/product/product_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:meal_planner/data/local/models/image.model.dart' as _i9;
import 'package:meal_planner/data/local/models/product.model.dart' as _i2;
import 'package:meal_planner/data/local/repository/local/local.product.repository.dart'
    as _i4;
import 'package:meal_planner/domain/abstract/repository.dart' as _i8;
import 'package:meal_planner/domain/entities/product/product.entity.dart'
    as _i3;
import 'package:meal_planner/utils/result.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductModel_0 extends _i1.SmartFake implements _i2.ProductModel {
  _FakeProductModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductEntity_1 extends _i1.SmartFake implements _i3.ProductEntity {
  _FakeProductEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalProductRepository extends _i1.Mock
    implements _i4.LocalProductRepository {
  MockLocalProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.ProductModel>> fetchAll() => (super.noSuchMethod(
        Invocation.method(
          #fetchAll,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.ProductModel>>.value(<_i2.ProductModel>[]),
      ) as _i5.Future<List<_i2.ProductModel>>);

  @override
  _i5.Future<_i2.ProductModel?> fetchById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchById,
          [id],
        ),
        returnValue: _i5.Future<_i2.ProductModel?>.value(),
      ) as _i5.Future<_i2.ProductModel?>);

  @override
  _i5.Future<void> insertModel(_i2.ProductModel? model) => (super.noSuchMethod(
        Invocation.method(
          #insertModel,
          [model],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateModel(_i2.ProductModel? model) => (super.noSuchMethod(
        Invocation.method(
          #updateModel,
          [model],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeModel(_i2.ProductModel? model) => (super.noSuchMethod(
        Invocation.method(
          #removeModel,
          [model],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  String idOf(_i2.ProductModel? model) => (super.noSuchMethod(
        Invocation.method(
          #idOf,
          [model],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #idOf,
            [model],
          ),
        ),
      ) as String);

  @override
  String entityIdOf(_i3.ProductEntity? entity) => (super.noSuchMethod(
        Invocation.method(
          #entityIdOf,
          [entity],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #entityIdOf,
            [entity],
          ),
        ),
      ) as String);

  @override
  _i2.ProductModel toWriteModel(_i3.ProductEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #toWriteModel,
          [entity],
        ),
        returnValue: _FakeProductModel_0(
          this,
          Invocation.method(
            #toWriteModel,
            [entity],
          ),
        ),
      ) as _i2.ProductModel);

  @override
  _i3.ProductEntity toEntity(_i2.ProductModel? model) => (super.noSuchMethod(
        Invocation.method(
          #toEntity,
          [model],
        ),
        returnValue: _FakeProductEntity_1(
          this,
          Invocation.method(
            #toEntity,
            [model],
          ),
        ),
      ) as _i3.ProductEntity);

  @override
  _i5.Future<_i7.Result<List<_i3.ProductEntity>>> getProductsForRecipe(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsForRecipe,
          [id],
        ),
        returnValue: _i5.Future<_i7.Result<List<_i3.ProductEntity>>>.value(
            _i6.dummyValue<_i7.Result<List<_i3.ProductEntity>>>(
          this,
          Invocation.method(
            #getProductsForRecipe,
            [id],
          ),
        )),
      ) as _i5.Future<_i7.Result<List<_i3.ProductEntity>>>);

  @override
  _i5.Future<void> onAfterInsert(_i3.ProductEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #onAfterInsert,
          [entity],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> onBeforeDelete(_i3.ProductEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #onBeforeDelete,
          [entity],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i7.Result<List<_i3.ProductEntity>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i5.Future<_i7.Result<List<_i3.ProductEntity>>>.value(
            _i6.dummyValue<_i7.Result<List<_i3.ProductEntity>>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i5.Future<_i7.Result<List<_i3.ProductEntity>>>);

  @override
  _i5.Future<_i7.Result<_i3.ProductEntity?>> getById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i5.Future<_i7.Result<_i3.ProductEntity?>>.value(
            _i6.dummyValue<_i7.Result<_i3.ProductEntity?>>(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i5.Future<_i7.Result<_i3.ProductEntity?>>);

  @override
  _i5.Future<_i7.Result<void>> add(_i3.ProductEntity? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [data],
        ),
        returnValue:
            _i5.Future<_i7.Result<void>>.value(_i6.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #add,
            [data],
          ),
        )),
      ) as _i5.Future<_i7.Result<void>>);

  @override
  _i5.Future<_i7.Result<List<void>>> addAll(List<_i3.ProductEntity>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [data],
        ),
        returnValue: _i5.Future<_i7.Result<List<void>>>.value(
            _i6.dummyValue<_i7.Result<List<void>>>(
          this,
          Invocation.method(
            #addAll,
            [data],
          ),
        )),
      ) as _i5.Future<_i7.Result<List<void>>>);

  @override
  _i5.Future<_i7.Result<void>> update(_i3.ProductEntity? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [data],
        ),
        returnValue:
            _i5.Future<_i7.Result<void>>.value(_i6.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #update,
            [data],
          ),
        )),
      ) as _i5.Future<_i7.Result<void>>);

  @override
  _i5.Future<_i7.Result<List<void>>> updateAll(List<_i3.ProductEntity>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAll,
          [data],
        ),
        returnValue: _i5.Future<_i7.Result<List<void>>>.value(
            _i6.dummyValue<_i7.Result<List<void>>>(
          this,
          Invocation.method(
            #updateAll,
            [data],
          ),
        )),
      ) as _i5.Future<_i7.Result<List<void>>>);

  @override
  _i5.Future<_i7.Result<void>> delete(_i3.ProductEntity? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [data],
        ),
        returnValue:
            _i5.Future<_i7.Result<void>>.value(_i6.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #delete,
            [data],
          ),
        )),
      ) as _i5.Future<_i7.Result<void>>);

  @override
  _i5.Future<_i7.Result<List<void>>> deleteAll(List<_i3.ProductEntity>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [data],
        ),
        returnValue: _i5.Future<_i7.Result<List<void>>>.value(
            _i6.dummyValue<_i7.Result<List<void>>>(
          this,
          Invocation.method(
            #deleteAll,
            [data],
          ),
        )),
      ) as _i5.Future<_i7.Result<List<void>>>);
}

/// A class which mocks [FileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileRepository extends _i1.Mock implements _i8.FileRepository {
  MockFileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i7.Result<String>> insert(_i9.ImageModel? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [data],
        ),
        returnValue: _i5.Future<_i7.Result<String>>.value(
            _i6.dummyValue<_i7.Result<String>>(
          this,
          Invocation.method(
            #insert,
            [data],
          ),
        )),
      ) as _i5.Future<_i7.Result<String>>);

  @override
  _i5.Future<_i7.Result<List<String>>> insertAll(List<_i9.ImageModel>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAll,
          [data],
        ),
        returnValue: _i5.Future<_i7.Result<List<String>>>.value(
            _i6.dummyValue<_i7.Result<List<String>>>(
          this,
          Invocation.method(
            #insertAll,
            [data],
          ),
        )),
      ) as _i5.Future<_i7.Result<List<String>>>);

  @override
  _i5.Future<_i7.Result<void>> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue:
            _i5.Future<_i7.Result<void>>.value(_i6.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #delete,
            [id],
          ),
        )),
      ) as _i5.Future<_i7.Result<void>>);

  @override
  _i5.Future<_i7.Result<void>> deleteAll(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [id],
        ),
        returnValue:
            _i5.Future<_i7.Result<void>>.value(_i6.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #deleteAll,
            [id],
          ),
        )),
      ) as _i5.Future<_i7.Result<void>>);
}
